version: '3.9'
services:
  e-bidder-db:
    image: postgres
    restart: always
    container_name: e-bidder-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=ebidder
      - PG_DATA=/data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
